tag: default
loglevel: 1
luppath: '/afs/desy.de/user/k/korcariw/geo_ex/src/output/DetIdLUT.root'
geoyamlpath: '/afs/desy.de/user/k/korcariw/geo_ex/src/output/geometry.yaml'
graphpath: '/afs/desy.de/user/k/korcariw/geo_ex/src/output/graph.pth'
mapper:
  threshold: 1e-02
  nevents: 1000
  xyz: ['recHit_x', 'recHit_y', 'recHit_z']
  calo_img_shape: [269, 254, 56]
  energy_threshold: 0.2
cores: 5
train:
  train_test_split: 0.2
predict:
  nevents: 100
model:
  gan:
    batch_size : 512
    n_epochs : 100
    sample_size : 64  # fixed sample size
    nz : 128  # latent vector size
    k : 1  # number of steps to apply to the discriminator
    lr : 0.0002
